### PR TITLE
RTL support

### LINKED ISSUE #59: RTL functions backwards
In RTL:
Moving the first column to the second, puts it second from last.
Moving the first column to the third puts it third from last.
etc.

### PR DESCRIPTION
**Pull request by YehudahA**
fix #59

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I'm not sure I'll pull this in directly, as I'm sure we can do it without duplicating logic, but that's a very useful implementation.

If we include it (in whole or part) are you happy for it to be included under the MIT license?

**Comment by YehudahA** [comment]
> Thanks for this! I'm not sure I'll pull this in directly, as I'm sure we can do it without duplicating logic, but that's a very useful implementation.
Of course. DRI is always better.

> If we include it (in whole or part) are you happy for it to be included under the MIT license?
Yes.

**Comment by YehudahA** [comment]
I rewrite the code, and remove duplicated logic.

**Comment by DataTables** [comment]
That looks sharp - thanks!

**Comment by YehudahA** [comment]
This code developed by Urban-Digital team!

**Pull request merged**
